# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo Hello, from app1!
          echo "tag=${{GITHUB_RUN_ID}}"
          echo $tag
      - name: Set the tag
        run: |
          if [ -z "${{tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{tag}}" >> $GITHUB_ENV
          fi

  docker:
    uses: supriyashevate/my-common-workflow/.github/workflows/docker-image.yml@master
    with:
      image_name: my-awesome-app
      tag: '${{tag}}'
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

