name: Docker Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      tag_name: $(date +%s)
      
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag supriyashevate/my-awesome-app:latest
      
    - name: Docker Push
      run: docker push supriyashevate/my-awesome-app
