name: Docker Image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true
        
jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
        
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set the tag
      run: |
        if [ -z "${{inputs.tag}}" ]
        then
          echo "final_tag=latest" >> $GITHUB_ENV
          echo "${{GITHUB_RUN_ID}}"
        else
          echo "final_tag=${{GITHUB_RUN_ID}}" >> $GITHUB_ENV
        fi
          
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        push: true
        tags: ${{secrets.DOCKER_USER}}/${{inputs.image_name}}:${{env.final_tag}}

