name: Docker Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      tag_name: $(date +%s)
      
    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: supriyashevate/my-awesome-app:v123
        tag_with_ref: true
        tag_with_sha: true
